name: Automation PR

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-tasks:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: assign reviewers
        id: assign_step # 이 ID가 두 스텝을 이어주는 다리 역할을 합니다.
        uses: actions/github-script@v6
        env:
          SCRIPT_FULL_PATH: ${{ github.workspace }}/.github/workflows/scripts/assign-reviewers.js
        with:
          script: |
            const assignScript = await import(process.env.SCRIPT_FULL_PATH);
            await assignScript.default({github, context, core});

      - name: send discord notification
        uses: actions/github-script@v6
        env:
          SCRIPT_FULL_PATH: ${{ github.workspace }}/.github/scripts/notifier_pr.js
          # 앞 스텝에서 core.setOutput("reviewers", ...)로 내뱉은 값을 여기서 받습니다.
          ASSIGNED_REVIEWERS: ${{ steps.assign_step.outputs.reviewers }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID_PR }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN_NOTIFIER }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { default: notify } = await import(process.env.SCRIPT_FULL_PATH);
            await notify({ github, context, core });
