name: Create Goal Track Week

on:
  issues:
    types: [opened, labeled]
  workflow_dispatch:

jobs:
  create_weeks:
    if: |
      contains(github.event.issue.title, 'Week') && 
      contains(github.event.issue.title, '~') &&
      contains(github.event.issue.labels.*.name, 'epic')

    runs-on: ubuntu-latest

    permissions:
      issues: write
      repository-projects: write

    env:
      TITLE: ${{ github.event.issue.title }}
      BODY: ${{ github.event.issue.body }}
      PARENT_NODE_ID: ${{ github.event.issue.node_id }}
      SCRIPT_FULL_PATH: ${{ github.workspace }}/.github/scripts/create_goal_track_week.js
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: run JS script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { default: run } = await import(process.env.SCRIPT_FULL_PATH);
            await run({ github, context, core });
