name: Notifier Discussion

on:
  discussion:
    types: [created]
  workflow_dispatch:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    env:
      TITLE: ${{github.event.discussion.title || 'Discussion Title' }}
      USER: ${{github.event.discussion.user.login || 'User' }}
      URL: ${{github.event.discussion.html_url || 'https://github.com/planet-devo-k/solveit/discussions' }}
      DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID_SOLVEIT }}
      BOT_TOKEN: ${{ secrets.REMINDER_BOT_TOKEN }}
    steps:
      - name: notify discord on discussion created
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bot ${BOT_TOKEN}" \
            -d '{
              "embeds": [
                {
                  "title": "새 Discussion이 생성되었습니다",
                  "description": "새로운 의견이나 질문이 올라왔어요. 함께 확인해봐요",
                  "color": 5815039,
                  "fields": [
                    {
                      "name": "제목",
                      "value": "`'"${TITLE}"'`",
                      "inline": false
                    },
                    {
                      "name": "작성자",
                      "value": "'"${USER}"'",
                      "inline": true
                    },
                    {
                      "name": "링크",
                      "value": "[바로가기]('"${URL}"')",
                      "inline": true
                    }
                  ]
                }
              ]
            }' \
            "https://discord.com/api/v10/channels/${DISCORD_CHANNEL_ID}/messages")

          echo "Discord Response Code: $RESPONSE"
