name: Notifier PR

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    env:
      DISCORD_CHANNEL_ID: ${{secrets.DISCORD_CHANNEL_ID_PR}}
      BOT_TOKEN: ${{secrets.REMINDER_BOT_TOKEN}}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      pull-requests: read
      contents: read

    steps:
      - name: notify discord on PR created
        uses: actions/github-script@v7
        with:
          script: |
            try{
              let pr;
              let reviewers = "";

              for (let i = 0; i < 5; i++) {
                const response = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                });
                
                pr = response.data;

                if (pr.requested_reviewers && pr.requested_reviewers.length > 0) {
                  reviewers = pr.requested_reviewers.map(r => `@${r.login}`).join(", ");
                  console.log(`리뷰어 확인됨: ${reviewers}`);
                  break;
                }

                console.log(`리뷰어 배정 대기 중... (${i + 1}/5)`);
                await new Promise(resolve => setTimeout(resolve, 2000));
              }

              const discordPayload = {
                content: "새로운 PR이 생성되었습니다. 코드 리뷰가 기다리고 있어요.",
                embeds: [{
                  title: "NEW PR\n━━━━━━━━━━━━━━━━━━━━━━",
                  description: `[${pr.title}](${pr.html_url})`,
                  color: 5815039,
                  fields: [
                    { name: "작성자", value: pr.user.login, inline: true },
                    { name: "지정 리뷰어", value: reviewers || "지정 중...", inline: true },
                  ]
                }]
              };

              const res = await fetch(`https://discord.com/api/v10/channels/${process.env.DISCORD_CHANNEL_ID}/messages`, {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                  'Authorization': `Bot ${process.env.BOT_TOKEN}`
                },
                body: JSON.stringify(discordPayload)
              });

              if (!res.ok) throw new Error(`Discord API error: ${res.status}`);
                console.log("디스코드 알림 전송 완료");
            } catch (error) {
              console.error("알림 전송 실패:", error.message);
            }
