name: Reminder Solveit

on:
  schedule:
    - cron: "0 0 * * 0" # 매주 일요일 9:00 (KST, UTC+9)
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment variables
        run: |
          echo "DISCORD_CHANNEL_ID=${{ secrets.DISCORD_CHANNEL_ID_SOLVEIT }}"
          echo "REMINDER_BOT_TOKEN=${{ secrets.REMINDER_BOT_TOKEN }}"

      - name: send solveit reminder to discord
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bot ${{secrets.REMINDER_BOT_TOKEN}}" \
          -d '{
            "embeds": [
              {
                "title": "오늘 스터디 있는 날",
                "description": "함께 배우며 성장하는 시간! 이따 만나요~!",
                "color": 16374876,
                "fields": [
                  {
                    "name": "When",
                    "value": "✓ 매주 일요일 오후 10시"
                  }
                ]
              }
            ]
          }' \
          https://discord.com/api/v10/channels/${{secrets.DISCORD_CHANNEL_ID_SOLVEIT}}/messages)
          echo "Response: $RESPONSE"
