name: Reminder Solveit

on:
  schedule:
    - cron: "0 0 * * 0" # 매주 일요일 9:00 (KST, UTC+9)
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    env:
      DISCORD_CHANNEL_ID: ${{secrets.DISCORD_CHANNEL_ID_SOLVEIT}}
      REMINDER_BOT_TOKEN: ${{secrets.REMINDER_BOT_TOKEN}}
      SCRIPT_FULL_PATH: ${{ github.workspace }}/.github/scripts/reminder_solveit.js
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: send solveit reminder to discord
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { default: run } = await import(process.env.SCRIPT_FULL_PATH);
            await run({ github, context, core });
