name: Reminder PR

on:
  schedule:
    - cron: "0 0 * * 5" # 매주 금요일 9:00 (UTC 기준으로 금 00:00)
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    env:
      DISCORD_CHANNEL_ID: ${{secrets.DISCORD_CHANNEL_ID_PR}}
      REMINDER_BOT_TOKEN: ${{secrets.REMINDER_BOT_TOKEN}}
    steps:
      - name: check environment variables
        run: |
          echo "DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}"
          echo "REMINDER_BOT_TOKEN=${REMINDER_BOT_TOKEN}"

      - name: send pr reminder to discord
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bot ${REMINDER_BOT_TOKEN}" \
          -d '{
            "embeds": [
              {
                "title": "PR 리마인더",
                "description": "잊지 말고 PR 생성하고 코드 리뷰 하자~!",
                "color": 16374876,
                "fields": [
                  {
                    "name": "Deadline",
                    "value": " ✓ PR 토요일 자정 \n ✓ 리뷰 일요일 오후 8시"
                  }
                ]
              }
            ]
          }' \
          "https://discord.com/api/v10/channels/${DISCORD_CHANNEL_ID}/messages")

          echo "Response: $RESPONSE"
