name: Rule Monitor Week

on:
  schedule:
    - cron: "0 15 * * 6" # UTC 기준 (KST 일요일 0시)
    - cron: "0 11 * * 0" # UTC 기준 (KST 일요일 20시)
  workflow_dispatch:

jobs:
  monitor-rules:
    runs-on: ubuntu-latest

    env:
      DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID_ALERT }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN_NOTIFIER }}
      SCRIPT_FULL_PATH: ${{ github.workspace }}/.github/scripts/rule_monitor_week.js
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: run rule monitor week script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { default: run } = await import(process.env.SCRIPT_FULL_PATH);
            await run({ github, context, core });
